namespace MMA.Domain
{
    public class FileHelper
    {
        public static CFileType GetFileTypeFromMimeType(string mimeType)
        {
            return MimeToFileTypeMap.TryGetValue(mimeType, out var fileType) ? fileType : CFileType.Other;
        }

        private static readonly Dictionary<string, CFileType> MimeToFileTypeMap = new Dictionary<string, CFileType>()
        {
            { "image/jpeg", CFileType.Image },
            { "image/png", CFileType.Image },
            { "image/gif", CFileType.Image },
            { "image/bmp", CFileType.Image },
            { "image/tiff", CFileType.Image },
            { "image/webp", CFileType.Image },
            { "image/svg+xml", CFileType.Image },
            { "image/x-icon", CFileType.Image },
            { "image/vnd.microsoft.icon", CFileType.Image },
            { "image/vnd.wap.wbmp", CFileType.Image },
            { "image/apng", CFileType.Image },
            { "image/avif", CFileType.Image },
            { "image/heif", CFileType.Image },
            { "image/heic", CFileType.Image },
            { "image/heif-sequence", CFileType.Image },
            { "image/heic-sequence", CFileType.Image },
            { "image/jp2", CFileType.Image },
            { "image/jpx", CFileType.Image },
            { "image/jpm", CFileType.Image },
            { "image/mj2", CFileType.Image },
            { "image/ktx", CFileType.Image },
            { "image/ktx2", CFileType.Image },
            { "image/dng", CFileType.Image },
            { "image/arw", CFileType.Image },
            { "image/cr2", CFileType.Image },
            { "image/cr3", CFileType.Image },
            { "image/nef", CFileType.Image },
            { "image/orf", CFileType.Image },
            { "image/rw2", CFileType.Image },
            { "image/raf", CFileType.Image },
            { "image/sr2", CFileType.Image },
            { "image/x-adobe-dng", CFileType.Image },
            { "image/x-canon-cr2", CFileType.Image },
            { "image/x-canon-cr3", CFileType.Image },
            { "image/x-nikon-nef", CFileType.Image },
            { "image/x-olympus-orf", CFileType.Image },
            { "image/x-panasonic-rw2", CFileType.Image },
            { "image/x-sony-arw", CFileType.Image },
            { "image/x-sony-sr2", CFileType.Image },
            { "image/x-fuji-raf", CFileType.Image },
            { "image/x-samsung-srw", CFileType.Image },
            { "image/x-pentax-pef", CFileType.Image },
            { "image/x-hasselblad-3fr", CFileType.Image },
            { "image/x-leica-rwl", CFileType.Image },
            { "application/zip", CFileType.Zip },
            { "application/x-zip-compressed", CFileType.Zip },
            { "application/x-rar-compressed", CFileType.Zip },
            { "application/x-7z-compressed", CFileType.Zip },
            { "application/x-tar", CFileType.Zip },
            { "application/x-bzip2", CFileType.Zip },
            { "application/x-gzip", CFileType.Zip },
            { "application/x-xz", CFileType.Zip },
            { "application/x-lzip", CFileType.Zip },
            { "application/x-lzma", CFileType.Zip },
            { "application/x-lzop", CFileType.Zip },
            { "application/x-lz4", CFileType.Zip },
            { "application/x-bzip", CFileType.Zip },
            { "application/x-compress", CFileType.Zip },
            { "application/pdf", CFileType.PDF },
            { "application/vnd.ms-excel", CFileType.Excel },
            { "text/csv", CFileType.Excel },
            { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", CFileType.Excel },
            { "application/vnd.ms-powerpoint", CFileType.PowerPoint },
            { "application/vnd.openxmlformats-officedocument.presentationml.presentation", CFileType.PowerPoint },
            { "application/msword", CFileType.Word },
            { "application/vnd.openxmlformats-officedocument.wordprocessingml.document", CFileType.Word },
            { "application/vnd.oasis.opendocument.text", CFileType.Word },
            { "application/vnd.oasis.opendocument.spreadsheet", CFileType.Excel },
            { "application/vnd.oasis.opendocument.presentation", CFileType.PowerPoint },
            { "application/vnd.oasis.opendocument.graphics", CFileType.Image },
            { "application/vnd.oasis.opendocument.image", CFileType.Image },
            { "application/vnd.oasis.opendocument.formula", CFileType.Excel },
            { "application/vnd.oasis.opendocument.database", CFileType.Database },
            { "application/vnd.oasis.opendocument.chart", CFileType.Excel },
            { "application/vnd.oasis.opendocument.text-master", CFileType.Word },
            { "application/vnd.oasis.opendocument.text-web", CFileType.Word },
            { "application/vnd.oasis.opendocument.text-template", CFileType.Word },
            { "application/vnd.oasis.opendocument.spreadsheet-template", CFileType.Excel },
            { "application/vnd.oasis.opendocument.presentation-template", CFileType.PowerPoint },
            { "application/vnd.oasis.opendocument.graphics-template", CFileType.Image },
            { "application/vnd.oasis.opendocument.image-template", CFileType.Image },
            { "application/vnd.oasis.opendocument.formula-template", CFileType.Excel },
            { "application/vnd.oasis.opendocument.database-template", CFileType.Database },
            { "application/vnd.oasis.opendocument.chart-template", CFileType.Excel },
            { "application/vnd.oasis.opendocument.text-master-template", CFileType.Word },
            { "application/vnd.oasis.opendocument.text-web-template", CFileType.Word },
            { "application/mp4", CFileType.Video },
            { "video/mp4", CFileType.Video },
            { "text/plain", CFileType.TXT },
            { "audio/mpeg", CFileType.Audio },
            { "audio/wav", CFileType.Audio },
            { "audio/ogg", CFileType.Audio },
            { "audio/flac", CFileType.Audio },
            { "audio/aac", CFileType.Audio },
            { "audio/mp3", CFileType.Audio },
            { "audio/x-m4a", CFileType.Audio },
            { "audio/x-wav", CFileType.Audio },
            { "audio/x-aiff", CFileType.Audio },
            { "audio/x-ms-wma", CFileType.Audio },
            { "audio/x-ms-wax", CFileType.Audio },
            { "audio/x-realaudio", CFileType.Audio },
            { "audio/x-pn-realaudio", CFileType.Audio },
            { "audio/x-pn-realaudio-plugin", CFileType.Audio },
            { "audio/x-matroska", CFileType.Audio },
            { "audio/x-matroska-3gpp", CFileType.Audio },
            { "audio/x-matroska-ps", CFileType.Audio },
            { "audio/x-matroska-ps-3gpp", CFileType.Audio },
            { "text/html", CFileType.Html },
            { "application/x-msdownload", CFileType.MicrosoftDownload },
            
        };
    }
}